import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import Anthropic from "@anthropic-ai/sdk";
import { extractTextFromPdf } from "../utils/pdfUtils.js";
import { logger } from "../utils/logger.js";
import { logTokenUsage } from "../utils/usage.js";
import { readMultipart } from "../utils/multipart.js";

const anthropic = new Anthropic();

// Extract text from a PDF for AI detection
async function extractRoute(request: FastifyRequest, reply: FastifyReply) {
  try {
    const { files } = await readMultipart(request);
    const file = files[0];
    if (!file) return reply.code(400).send({ error: "No file uploaded" });
    const extracted = await extractTextFromPdf(file.buffer);
    const text = extracted.pages.map((p) => p.text).join("\n\n");
    return { success: true, text };
  } catch (err) {
    logger.error("AI detect extraction error", {
      error: err instanceof Error ? err.message : String(err),
    });
    return reply.code(500).send({ error: "Text extraction failed" });
  }
}

const DETECTION_PROMPT = `You are an expert AI-generated text detector. Your job is to determine whether a given text was written by a human or generated by an AI language model (ChatGPT, GPT-4, Claude, Gemini, etc.).

IMPORTANT: Be rigorous and skeptical. AI-generated text is extremely common now and you should err on the side of detecting it. Many documents that appear professional were actually AI-generated.

Evaluate these categories. Score each 0-100 where 0 = clearly human, 100 = clearly AI:

1. **Sentence Uniformity** (weight: HIGH): AI produces sentences of remarkably similar length and rhythm. Count the variation in sentence lengths — low variation = AI. Human writing has short punchy sentences mixed with long complex ones.

2. **AI Vocabulary & Phrases** (weight: HIGH): AI has telltale phrases it uses repeatedly:
   - "It is important to note", "It's worth noting", "It should be noted"
   - "Furthermore", "Moreover", "Additionally", "In addition"
   - "comprehensive", "robust", "facilitate", "leverage", "streamline"
   - "delve into", "navigate", "foster", "bolster", "underscore"
   - "In conclusion", "In summary", "Overall"
   - "plays a crucial role", "is essential for", "is paramount"
   - "In today's [X]", "In the realm of"
   - Excessive use of "ensure", "enhance", "optimize"
   - Lists with parallel structure (e.g., "First... Second... Third...")
   Even 2-3 of these in a short text is a strong AI signal.

3. **Paragraph Consistency** (weight: MEDIUM): AI paragraphs are suspiciously uniform in length (typically 3-5 sentences each). Human paragraphs vary wildly — some are one sentence, some are 10+.

4. **Hedging & Qualifiers** (weight: MEDIUM): AI overuses:
   - "may", "might", "could", "potentially", "generally"
   - "it is possible that", "depending on", "in some cases"
   - "typically", "often", "usually", "tends to"
   AI hedges to avoid being wrong. Humans are more direct and assertive.

5. **Naturalness & Voice** (weight: HIGH): The strongest signal. Human text has:
   - Typos, grammatical quirks, colloquialisms, contractions
   - Personal opinions stated directly ("I think", "We found")
   - Uneven quality — some sections polished, others rough
   - Domain-specific jargon used naturally (not defined/explained)
   - Emotional tone, frustration, humor, sarcasm
   AI text is uniformly polished, neutral in tone, explains everything, and lacks personal voice. If the text reads like a Wikipedia article or a corporate blog post, it's likely AI.

6. **Structural Patterns** (weight: MEDIUM): AI loves:
   - Introduction → body → conclusion format even in short texts
   - Numbered or bulleted lists
   - Topic sentences at the start of every paragraph
   - Smooth transitions between every paragraph
   - Balanced coverage of multiple perspectives

SCORING GUIDELINES:
- 0-20: Almost certainly human (clear personal voice, errors, irregular structure)
- 21-40: Likely human (some polish but natural variations present)
- 41-60: Uncertain (mixed signals — could be AI-edited human text or well-prompted AI)
- 61-80: Likely AI (multiple AI patterns, uniform structure, AI vocabulary)
- 81-100: Almost certainly AI (overwhelming AI patterns, no human markers)

The overallScore should be the WEIGHTED AVERAGE favoring the high-weight categories. Do NOT default to low scores — if you see AI patterns, score them high.

Return a JSON object:
{
  "overallScore": <0-100 integer>,
  "categories": {
    "sentenceUniformity": <0-100>,
    "aiVocabulary": <0-100>,
    "paragraphConsistency": <0-100>,
    "hedgingLanguage": <0-100>,
    "naturalness": <0-100>,
    "structuralPatterns": <0-100>
  },
  "confidence": "low" | "medium" | "high",
  "notes": "<2-3 sentence explanation of the key indicators found. Be specific — quote actual phrases from the text that triggered detection.>"
}

Only output valid JSON, no markdown code fences or extra text.`;

// ── GPTZero Integration ────────────────────────────────────────────────

async function callGPTZero(text: string, filename: string) {
  const apiKey = process.env.GPTZERO_API_KEY;
  if (!apiKey) throw new Error("GPTZero API key not configured");

  // GPTZero accepts up to ~50000 chars per request
  const truncated = text.length > 50000 ? text.slice(0, 50000) : text;

  const response = await fetch("https://api.gptzero.me/v2/predict/text", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      Accept: "application/json",
    },
    body: JSON.stringify({ document: truncated, multilingual: false }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`GPTZero API error ${response.status}: ${errText.slice(0, 200)}`);
  }

  const data = (await response.json()) as {
    documents?: Array<{
      class_probabilities?: Record<string, number>;
      completely_generated_prob?: number;
      confidence_category?: string;
      predicted_class?: string;
      sentences?: Array<{
        sentence?: string;
        generated_prob?: number;
        completely_generated_prob?: number;
        highlight_sentence_for_ai?: boolean;
      }>;
    }>;
  };
  const doc = data.documents?.[0];
  if (!doc) throw new Error("No document in GPTZero response");

  const classProbs = doc.class_probabilities || {};
  const aiProb = classProbs.ai ?? doc.completely_generated_prob ?? 0;
  const humanProb = classProbs.human ?? 0;
  const mixedProb = classProbs.mixed ?? 0;
  const overallScore = Math.round(aiProb * 100);

  const sentences = (doc.sentences || []).map((s) => ({
    text: s.sentence || "",
    generatedProb: s.generated_prob ?? s.completely_generated_prob ?? 0,
    highlight: s.highlight_sentence_for_ai === true || (s.generated_prob ?? 0) > 0.5,
  }));

  let label: string;
  if (overallScore >= 70) label = "Likely AI-generated";
  else if (overallScore >= 30) label = "Mixed (possibly AI + human)";
  else label = "Likely human-written";

  return {
    provider: "GPTZero",
    overallScore,
    categories: {
      aiProbability: Math.round(aiProb * 100),
      humanProbability: Math.round(humanProb * 100),
      mixedProbability: Math.round(mixedProb * 100),
      completelyGenerated: Math.round((doc.completely_generated_prob ?? 0) * 100),
    },
    confidence: doc.confidence_category || "medium",
    notes:
      label +
      ". " +
      (doc.predicted_class ? "GPTZero predicted class: " + doc.predicted_class + "." : "") +
      " Based on " +
      sentences.length +
      " sentence(s) analyzed.",
    sentences,
    filename,
  };
}

async function detectRoute(request: FastifyRequest, reply: FastifyReply) {
  try {
    const { text, filename } = (request.body ?? {}) as { text?: string; filename?: string };
    if (!text || text.length < 100) {
      return reply
        .code(400)
        .send({ error: "Text too short for analysis (minimum 100 characters)" });
    }

    // Try GPTZero first
    if (process.env.GPTZERO_API_KEY) {
      try {
        const gptzResult = await callGPTZero(text, filename || "Unknown");
        return { success: true, ...gptzResult };
      } catch (err) {
        logger.warn("GPTZero failed, falling back to Claude", {
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    // Fallback: Claude-based detection
    let sample = "";
    if (text.length <= 15000) {
      sample = text;
    } else {
      const chunkSize = 5000;
      const beginning = text.slice(0, chunkSize);
      const middleStart = Math.floor(text.length / 2) - Math.floor(chunkSize / 2);
      const middle = text.slice(middleStart, middleStart + chunkSize);
      const end = text.slice(-chunkSize);
      sample =
        beginning +
        "\n\n[...middle section...]\n\n" +
        middle +
        "\n\n[...later section...]\n\n" +
        end;
    }

    // Run detection twice and average for consistency
    const runDetection = async () => {
      const response = await anthropic.messages.create({
        model: "claude-sonnet-4-20250514",
        max_tokens: 1024,
        temperature: 0,
        system: DETECTION_PROMPT,
        messages: [
          {
            role: "user",
            content:
              "Analyze this text for AI-generated content. Be thorough and skeptical. Remember: if you see AI patterns, score them HIGH, not low.\n\n" +
              sample,
          },
        ],
      });
      logTokenUsage("ai-detect", response.usage);
      const tb = response.content.find((b) => b.type === "text");
      if (!tb || tb.type !== "text") throw new Error("No response");
      let raw = tb.text.trim();
      if (raw.startsWith("```"))
        raw = raw.replace(/^```(?:json)?\s*\n?/, "").replace(/\n?```\s*$/, "");
      try {
        return JSON.parse(raw);
      } catch {
        const m = raw.match(/\{[\s\S]*\}/);
        if (m) return JSON.parse(m[0]);
        throw new Error("Parse failed");
      }
    };

    // Run twice in parallel
    const [result1, result2] = await Promise.all([runDetection(), runDetection()]);

    // Average the scores — take the HIGHER of the two overall scores (err on side of detection)
    const result: {
      overallScore: number;
      categories: Record<string, number>;
      [k: string]: unknown;
    } = { ...result1 };
    result.overallScore = Math.max(result1.overallScore || 0, result2.overallScore || 0);
    if (result1.categories && result2.categories) {
      for (const key of Object.keys(result1.categories)) {
        result.categories[key] = Math.round(
          Math.max(result1.categories[key] || 0, result2.categories[key] || 0),
        );
      }
    }
    // Use the notes from whichever run scored higher
    if ((result2.overallScore || 0) > (result1.overallScore || 0)) {
      result.notes = result2.notes;
      result.confidence = result2.confidence;
    }

    return {
      success: true,
      provider: "Claude (fallback)",
      filename: filename || "Unknown",
      ...result,
    };
  } catch (error) {
    logger.error("AI detection error", {
      error: error instanceof Error ? error.message : String(error),
    });
    if (error instanceof Anthropic.APIError) {
      return reply.code(500).send({ error: "Claude API error: " + error.message });
    }
    return reply.code(500).send({ error: "AI detection failed" });
  }
}

export default async function aiDetect(app: FastifyInstance) {
  app.post("/extract", { schema: { tags: ["ai-detect"] } }, extractRoute);
  app.post("/", { schema: { tags: ["ai-detect"] } }, detectRoute);
}
