apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secretproviderclass.yaml
- pvc.yaml
patches:
- path: deployment-patch.yaml
namespace: doc-analyzer-dev
replicas:
- count: 2
  name: doc-analyzer
images:
- name: ghcr.io/dc-bar-web/odc-poc
  newTag: sha-7bc8882