apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doc-analyzer-staging-storage
  labels:
    app: doc-analyzer
    env: staging
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs-dynamic
  resources:
    requests:
      storage: 1Gi